repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [
          '--py311-plus',
        ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [
          '--line-length=120',
          '--skip-string-normalization',
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [
          '--line-length=120',
          '--profile=black',
          '--filter-files',
          '--force-single-line-imports',
          '--reverse-relative',
        ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'pycodestyle==2.11.1',  # E,W
          'pyflakes==3.2.0',  # F
          'mccabe==0.7.0',  # C
          'flake8-bugbear==24.2.6',  # B
          'flake8-builtins==2.2.0',  # A
          'flake8-comprehensions==3.14.0',  # C4
          'flake8-tidy-imports==4.10.0',  # I
          'flake8-datetime-import==0.1.0',  # DTI
          'flake8-debugger==4.1.2',  # T1
          'flake8-logging==1.5.0',  # LOG
          'flake8-use-fstring==1.4.0',  # FS
          'flake8-print==5.0.0',  # T2
        ]
        args: [
          '--select=E,W,F,C,B,A,C4,I,DTI,T1,LOG,FS,T2',
          '--ignore=E203,W503,B008,B305,A003',
          '--ban-relative-imports=parents',
          '--max-complexity=10',
          '--max-line-length=120',
        ]

  - repo: https://github.com/myint/docformatter
    rev: 06907d0
    hooks:
      - id: docformatter
        args: [
          '--wrap-summaries=120',
          '--wrap-descriptions=120',
          '--in-place',
        ]
